name: CI with Dependency Caching

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-cache-2e61f2f-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Prime Cache State
        id: prime-cache-2e61f2f
        run: |
          echo "cache state: ${{ steps.cache-deps.outputs.cache-hit }}"
          echo "cache_path=${{ steps.cache-deps.outputs.cache-hit }}" >> $GITHUB_OUTPUT

      - name: Run Tests
        run: npm test

