name: Cache Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-2e61f2f
          restore-keys: |
            cache-2e61f2f

      - name: prime-cache-2e61f2f
        run: |
          if [ -n "${{ steps.cache-step.outputs.cache-hit }}" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
